### ISSUE TITLE
Bot deletes messages

### ISSUE THREAD

**Issue by alexsgocart** [Rasmusb94/ElevenlabsTTSBot#1]
Super cool bot. I got it working on my discord server but it keeps deleting messages. How can I get it to stop auto-deleting messages?

**Comment by alexsgocart** [comment]
I resolved the issue

**Comment by Rasmusb94** [comment]
Awesome, I'm glad you like it. 
I made it automatically remove the messages after a little while to stop channels from being spammed with bot commands.
