### ISSUE TITLE
Additional Voices 

### ISSUE THREAD

**Issue by Rmwsmith** [Rasmusb94/ElevenlabsTTSBot#2]
Is there any way to add more voices for Eleven Labs Voice library?

**Comment by Rmwsmith** [comment]
Modified the Bot code to
@bot.command(pass_context=True, name="tts", help="Use tts Voice message, example: " + PREFIX + "'tts Adam 50 Hello World' param: <Voice or random> <Stability 1-100> <Message>")
async def _tts(ctx, name, stability, *args):
    voice = await getvoice(ctx)
    try:
        botmessage = " ".join(args[:])
        ttsvoice = name.capitalize()
        voicedata = voices()
        counter = 0
        stablecheck = int(stability)
        randomvoice = False
        if stablecheck > 100:
            stability = '50'
        else:
            stablecheck = float(stablecheck / 100)
            stability = str(stablecheck)
        if ttsvoice == "Random":
            randomvoice = True
            randommax = len(voicedata)
            voicenum = random.randrange(0, randommax)
            voiceid = voicedata[voicenum].voice_id
            ttsvoice = voicedata[voicenum].name
        elif ttsvoice == "(Name of the Voice)":
            voiceid = '(ID of the Voice in Elevenlabs)'
        else:
            for i in voicedata:
                if ttsvoice == voicedata[counter].name:
                    voiceid = voicedata[counter].voice_id
                counter += 1

**Comment by Rasmusb94** [comment]
Custom voices added in v1.1.1
This code is deprecated
